### ISSUE TITLE
KMK Taipo: make_key( ... ) not working

### ISSUE THREAD

**Issue by Glodigit** [dlip/chouchou#1]
The code:
```
86: for key, code in taipo_keycodes.items():
87:           make_key( names=(key,), meta=TaipoMeta(code))
```
The response:
```
Traceback (most recent call last):
  File "code.py", line 15, in <module>
  File "kb.py", line 105, in __init__
  File "taipo.py", line 87, in __init__
  File "kmk/keys.py", line 554, in make_key
TypeError: unexpected keyword argument 'meta'
```
It seems KMK changed how the make_keys function works in [keys.py](https://github.com/KMKfw/kmk_firmware/blob/main/kmk/keys.py) between last year and now.

**Comment by Glodigit** [comment]
Solution:
```
class TaipoKey(Key):
    def __init__(self, code: Optional[int] = None):
        self.taipo_code = code    
    def __repr__(self):
        return super().__repr__() + '(' + str(self.taipo_code) + ')'

class Taipo(Module):
    def __init__(self...):
        {...}
        for name, code in taipo_keycodes.items():
            make_key(
                names=(name,),
                constructor=TaipoKey,
                code=code,
                )
```
